language: python
python: 3.5
sudo: false
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
